//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetaJob.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class curtisGodaddyEntities : DbContext
    {
        public curtisGodaddyEntities()
            : base("name=curtisGodaddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<JobListing> JobListings { get; set; }
        public virtual DbSet<JobSearch> JobSearches { get; set; }
        public virtual DbSet<JobSearchActivity> JobSearchActivities { get; set; }
        public virtual DbSet<TargetCompany> TargetCompanies { get; set; }
        public virtual DbSet<DropDownValue> DropDownValues { get; set; }
        public virtual DbSet<GetaJob_User> GetaJob_User { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobListingRequirement> JobListingRequirements { get; set; }
        public virtual DbSet<JobSkill> JobSkills { get; set; }
    }
}
