//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetaJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string UserId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<System.DateTime> Terminated { get; set; }
        public string Explanation { get; set; }
        public string JobTitle { get; set; }
    }
}
