//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetaJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobListingRequirement
    {
        public int JobListingRequirementId { get; set; }
        public Nullable<int> JobListingId { get; set; }
        public Nullable<int> JobSkillId { get; set; }
        public Nullable<int> DesiredId { get; set; }
    }
}
