//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetaJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSearch()
        {
            this.JobListings = new HashSet<JobListing>();
        }
    
        public int JobSearchId { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobListing> JobListings { get; set; }
    }
}
