//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetaJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSkill
    {
        public int JobSkillId { get; set; }
        public int JoId { get; set; }
        public string JobSkillTitle { get; set; }
        public string JobSkill1 { get; set; }
        public Nullable<int> JobSkillType { get; set; }
    }
}
